### ISSUE TITLE
Will support cuda9.0?

### ISSUE THREAD

**Issue by ysh329** [ufoym/deepo#1]
Thanks in advance! 😄

**Comment by ufoym** [comment]
Unfortunately, some frameworks do not support CUDA 9 currently. We will keep track of updates.

**Comment by ysh329** [comment]
Thanks your reply 😆

**Comment by crawld** [comment]
I'm running the all-py27-jupyter image, and when I try to import keras libraries, I get:

```
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
```
So it looks like tensorflow is now using cuda9.

**Comment by ufoym** [comment]
Deepo is now moving to CUDA 9.0 & cuDNN 7, though we are still working on bug fixes.
New docker images are expected to be available soon.

**Comment by ufoym** [comment]
CUDA 9.0 is now supported.

**Comment by crawld** [comment]
thanks!
