### ISSUE TITLE
matplotlib.pyplot error when importing: ImportError: No module named '_tkinter', please install the python3-tk package

### ISSUE THREAD

**Issue by lucasrodes** [ufoym/deepo#17]
It looks like there is some package missing (python3-tk?), which prevents from normal usage of `matplotlib.pyplot`. Is there any workaround for this issue? Thanks!

```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 37, in <module>
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/tkinter/__init__.py", line 39, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
```

**Comment by ufoym** [comment]
When you want to generate images without having a window appear, we suggest using a non-interactive backend such as `agg`. In your figure-generating script, just call the `matplotlib.use()` directive before importing pylab or pyplot:
```python
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.savefig('myfig')
```

**Comment by lucasrodes** [comment]
Hi Thanks for your rapid response. I used `matplotlib.use('agg')` and it worked.

**Comment by tunveyyy** [comment]
using matplotlib.use('Agg') did not work for me and shows the following error
>>> import matplotlib
>>> matplotlib.use('Agg')
__main__:1: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "<stdin>", line 1, in <module>
  File "/home/tunveyyy/virtualenv_python3/env/lib/python3.4/site-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/tunveyyy/virtualenv_python3/env/lib/python3.4/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

**Comment by lucasrodes** [comment]
Hi, did you try with lower case? 

```python
import matplotlib
matplotlib.use('agg')
```

**Comment by ksajjan** [comment]
Hi, In the below case

`This call to matplotlib.use() has no effect because the backend has already`

Just restart the terminal.
