### ISSUE TITLE
Error when import lasagne and theano

### ISSUE THREAD

**Issue by ldong87** [ufoym/deepo#54]
Thanks for the one-stop DL docker files. I'm using the all-jupyter-py36-cu90 and found the following errors when importing theano and lasagne.

>>> import theano
/usr/local/lib/python3.6/dist-packages/theano/tests/main.py:6: DeprecationWarning: Importing from numpy.testing.nosetesteris deprecated, import from numpy.testing instead.
  from numpy.testing.nosetester import NoseTester
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/theano/__init__.py", line 156, in <module>
    import theano.gpuarray
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/__init__.py", line 33, in <module>
    from . import fft, dnn, opt, extra_ops, multinomial, reduction, sort, rng_mrg, ctc
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/opt.py", line 2801, in <module>
    from .dnn import (local_abstractconv_cudnn,
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 339, in <module>
    handle_type = CUDNNDataType('cudnnHandle_t', 'cudnnDestroy')
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 259, in CUDNNDataType
    version=version(raises=False))
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 319, in version
    if not dnn_present():
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 209, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 180, in _dnn_check_version
    v = version()
  File "/usr/local/lib/python3.6/dist-packages/theano/gpuarray/dnn.py", line 334, in version
    "while the library is version %s." % v)
RuntimeError: Mixed dnn version. The header is version 7201 while the library is version 7102.

>>> import lasagne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/lasagne/__init__.py", line 12, in <module>
    import theano
  File "/usr/local/lib/python3.6/dist-packages/theano/__init__.py", line 144, in <module>
    if hasattr(theano.tests, "TheanoNoseTester"):
AttributeError: module 'theano' has no attribute 'tests'

**Comment by ufoym** [comment]
Fixed.
